#spring configuration
spring:
  application:
    name: cloudApi
  mustache:
    suffix: .html
    
#custom configuration (액세스 키 ID, Secret 기본 값은 본인 로컬에 있는 Credential참조 ) , 정책 arn은 aws 참조
application:
  aws:
    username : Users
    accessKeyId: AKIAZZL2R2GQNGLEYS5Z
    accessKeySecret: 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
    policy_arn: arn:aws:iam::aws:policy/AmazonEC2FullAccess